// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmuvgyoemeghfmizibvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtdXZneW9lbWVnaGZtaXppYnZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzODg5MTIsImV4cCI6MjA2OTk2NDkxMn0.EUWalWCaaG1aMIMYTde61NVpE9OsADoHWk8zpzzPdqQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});